# Site settings
title: Go Web Framework
email: pusic007@gmail.com
description: Go Web Framework
baseurl: ""
godoc: "https://godoc.org/github.com/ivpusic/neo"
github: "https://github.com/ivpusic/neo"
url: "https://ivpusic.github.io/neo"
#url: "http://localhost:4000"
twitter_username: ivpusic
github_username:  ivpusic

# Build settings
markdown: kramdown

highlighter: rouge

sass:
  sass_dir: _sass
